# '''
# GUI for running the Closed Loop Auditory Stimulation experiment
# Author: Simeon Wong
# '''

# import sys
# import traceback

# # Qt Framework
# from typing import Callable
# from PyQt5 import QtWidgets, uic
# from PyQt5.QtCore import QRunnable, QTimer, Qt, QThreadPool, QPoint
# from PyQt5.QtGui import QPainter, QColor, QBrush, QPen, QStaticText
# from PyQt5.QtWidgets import QComboBox, QDateTimeEdit, QWidget, QFileDialog
# import qdarkstyle

# import os
# import io
# import json
# import struct
# import time
# from enum import Enum
# from typing import Optional
# import logging
# import psutil
# import yaml

# # Plot stuff
# import matplotlib, matplotlib.figure
# import matplotlib.pyplot as plt
# from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg

# # Math stuff
# import numpy as np

# # CLAS algorithm
# import QCLASAlgo

# # Misc
# import datetime

# # for Pushover
# import requests
# import yaml


# class Main(QtWidgets.QMainWindow):
#     def __init__(self, parent: QWidget | None = ..., flags: Qt.WindowFlags | Qt.WindowType = ...) -> None:
#         super().__init__(parent, flags)

# if __name__ == "__main__":
#     App = QtWidgets.QApplication(sys.argv)
#     window = Main()
#     sys.exit(App.exec())

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'my_ui_file.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow: QtWidgets.QMainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1182, 624)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setWindowTitle("CLAS at Home")
        
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        
        self.timeseries_widget = QtWidgets.QWidget(self.centralwidget)
        self.timeseries_widget.setGeometry(QtCore.QRect(10, 10, 1161, 281))
        self.timeseries_widget.setObjectName("timeseries_widget")
        
        self.btn_start = QtWidgets.QPushButton(self.centralwidget)
        self.btn_start.setGeometry(QtCore.QRect(10, 330, 75, 51))
        self.btn_start.setObjectName("btn_start")
        
        self.btn_stop = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stop.setGeometry(QtCore.QRect(90, 330, 251, 51))
        self.btn_stop.setObjectName("btn_stop")
        
        self.status = QtWidgets.QPushButton(self.centralwidget)
        self.status.setEnabled(False)
        self.status.setGeometry(QtCore.QRect(10, 300, 331, 23))
        self.status.setObjectName("status")
        
        self.pleth_widget = QtWidgets.QWidget(self.centralwidget)
        self.pleth_widget.setGeometry(QtCore.QRect(350, 310, 671, 80))
        self.pleth_widget.setObjectName("pleth_widget")
        
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(350, 300, 47, 13))
        self.label_2.setObjectName("label_2")
        
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(350, 400, 101, 16))
        self.label_3.setObjectName("label_3")
        
        self.accl_widget = QtWidgets.QWidget(self.centralwidget)
        self.accl_widget.setGeometry(QtCore.QRect(350, 420, 671, 80))
        self.accl_widget.setObjectName("accl_widget")
        
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(350, 500, 71, 16))
        self.label_4.setObjectName("label_4")
        
        self.pll_widget = QtWidgets.QWidget(self.centralwidget)
        self.pll_widget.setGeometry(QtCore.QRect(350, 520, 671, 80))
        self.pll_widget.setObjectName("pll_widget")
        
        self.btn_screenoff = QtWidgets.QPushButton(self.centralwidget)
        self.btn_screenoff.setGeometry(QtCore.QRect(10, 390, 75, 23))
        self.btn_screenoff.setObjectName("btn_screenoff")
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CLAS at Home"))
        self.btn_start.setText(_translate("MainWindow", "Start"))
        self.btn_stop.setText(_translate("MainWindow", "STOP"))
        self.status.setText(_translate("MainWindow", "Stopped..."))
        self.label_2.setText(_translate("MainWindow", "Pleth"))
        self.label_3.setText(_translate("MainWindow", "Accelerometry"))
        self.label_4.setText(_translate("MainWindow", "PLL status"))
        self.btn_screenoff.setText(_translate("MainWindow", "screen off"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())